# -*- Makefile for vim config files -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>

VIM_DIR=~/.vim/

.PHONY: all
all:
	ln -i -s ${PWD}/vimrc ${HOME}/.vimrc
	ln -i -s ${PWD}/.vim ${HOME}/.vim

	@echo ""
	@echo "Vim Setup Config complete"

