# -*- Makefile for ssh config files -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>

.PHONY: all
all:
	mkdir -p ${HOME}/.ssh/
	ln -i -s ${PWD}/config ${HOME}/.ssh/config

	@echo ""
	@echo "SSH configuration setup complete"
