#!/bin/bash

###############
# shortcuts
###############
alias code='cl ${HOME}/Projects/'

###############
# cd & ls
###############
function cl {
        cd $1;
            ls
}
alias ..='cl ..'

alias ls="ls -G"


###############
# History
###############

alias hs="history | grep $1"




################
# PIP
################
export SYSTEM_PIP=`which pip`
function syspip {
    PIP_REQUIRE_VIRTUALENV="" sudo $SYSTEM_PIP "$@"
}
