#!/bin/bash

###############
# shortcuts
###############
alias code='cl ${HOME}/Projects/'

###############
# cd
###############
function cl {
        cd $1;
            ls
}
alias ..='cl ..'


###############
# History
###############

alias hs="history | grep $1"
