all:
	cp org.saevon.pf.conf /etc/pf.anchors/
	chown root /etc/pf.anchors/org.saevon.pf.conf
	cp org.saevon.pf.rules /etc/pf.anchors/
	chown root /etc/pf.anchors/org.saevon.pf.rules

	cp org.saevon.pf.plist /Library/LaunchDaemons
	chown root /Library/LaunchDaemons/org.saevon.pf.plist
