# -*- Makefile for fortune files -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>

include ../variables.makefile

.PHONY: all
all: completion
	sudo bash -c "source ${PWD}/setup.sh"

	@echo ""
	@echo "Fortunes Setup Complete"


include ../completion.makefile










