# -*- Makefile for django autocompletion files -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>

.PHONY: all
all:
	ln -i -s ${PWD}/django_bash_completion.bash ${HOME}/.git/.django_bash_completion.bash

	@echo ""
	@echo "Django Autocompletion Setup complete, If you didn't run the"
	@echo "bash setup then the completion script won't work so watch out!"
