# -*- Makefile for git config files -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>

.PHONY: all
all:
	sudo bash -c "source ${PWD}/setup.sh"

	@echo ""
	@echo "Fortunes Setup Complete"











