# -*- Makefile for git config files -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>

.PHONY: all
all:
	sudo ln -i -s "/Applications/Sublime Text 2.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl

	@echo ""
	@echo "Sublime Text 2 Setup complete"
	@echo "Make sure Sublime Text 2 is installed"
	@echo "and watch out! This currently only works for OSX"
