# -*- makefile to copy over automator scripts -*-
# Copyright 2013 Saevon <saevon.kyomae@gmail.com>
SHELL = /bin/bash

.PHONY: all
all: 
	# TODO: this doesn't really work, since `.workflow` extension is a folder
	@cp * ${HOME}/Library/Services/

