#
# .bash_profile
# This file is loaded only when logging into a machine
# OSX: always re-runs it for each new terminal
#


# Load .profile, containing login, non-bash related initializations.
# aka ENV_VARIABLES
if [ -e $HOME/.profile ]; then
	source $HOME/.profile
fi

# Load .bashrc, containing non-login related bash initializations.
# Aliases,
if [ -e $HOME/.bashrc ]; then
	source $HOME/.bashrc
fi

# Used to load massive bashrc (aka when you slit it into seperate files)
# autocompletes
# if [[ -d $HOME/.bashrc.d ]] ; then
#     for bashrc in "$HOME"/.bashrc.d/*.bash ; do
# 	    source $bashrc
#     done
#     unset -v bashrc
# fi












